### ISSUE TITLE
README has out-of-date install instructions

### ISSUE THREAD

**Issue by joshwand** [bdbarnett/mpdisplay#12]
README is referring to /installers directory which no longer exists. Would appreciate current instructions on installing for MCU; the various current packages.json seem to install everything and the kitchen sink as opposed to being able to select modules as needed.

**Comment by tdhoward** [comment]
It seems like a lot of big organizational changes have been happening recently, so I'm not sure if this will be the best place to go, but it looks like Brad just recently added [this file](https://github.com/bdbarnett/mpdisplay/blob/main/docs/GETTING-STARTED.md), which has some good info in it.

**Comment by bdbarnett** [comment]
Hello @joshwand and @tdhoward!

I've changed a lot of the structure of the project and am in the process of changing the name to PyDevices.  The "getting started" file @tdhoward linked to is currently the best source of information for installing.  If you have any trouble at all, please let me know.  I want to help you get it working and I can create more installer scripts if needed.

Also, I'd like to know a little about how you are using it.  For example, are you using it with LVGL or not?  What environments are you using (for example CPython on WSL, MicroPython on an ESP32-S3, etc.)?  Have you tried to use it with `mpremote mount .` instead of copying the files to your device?  Does the Wokwi example help?  Is there anything else you can provide?

Much appreciated!

**Comment by tdhoward** [comment]
> Also, I'd like to know a little about how you are using it. For example, are you using it with LVGL or not? What environments are you using (for example CPython on WSL, MicroPython on an ESP32-S3, etc.)? 

@bdbarnett Thanks for all your work on this project!  I found it a couple months ago while looking for a way to use a st7796 driver chip with MicroPython.  I'm using a Lilygo T-Display-S3 Pro, which is a beautiful little device with an ESP32-S3 microcontroller.  I also have some T-Display-S3's around, which use the st7789 driver.  I've had some success with the T-Display-S3's, but wanted to get comfortable on those before creating a new board config for the T-Display-S3 Pro.

I decided against using LVGL for now, since it looked like I would need to create a special build of MicroPython for each different device type.  However, if the speed difference is substantial enough, I might have to go that route eventually.  I would much prefer using the generic MicroPython builds, though.

I've tried it with MicroPython on WSL, and got that working.  I should try it with CPython, too.

> Have you tried to use it with mpremote mount . instead of copying the files to your device?

I have not tried that yet.  I wrote a little CPython script to sync my PC files with a MicroPython filesystem, so I generally use that, since it's pretty quick.  But from what I hear, mpremote could be really handy.  I'll have to give it a try.

> Does the Wokwi example help?
I tried it out, and it looks like your mip.install packages need a 'pyd_' in front of them.  Once I changed that, they mostly downloaded okay, except for pyd_basedisplay.json, which still references some old filenames (_basedisplay_numpy.py and _basedisplay_viper.py).

> Is there anything else you can provide?
I'm working on an overly ambitious project that is aimed at teaching kids how to program using MicroPython on embedded device.  Basically, I want to be able to hand this battery-powered T-Display-S3 Pro to a kid, and they can start programming or exploring examples without installing drivers or doing any complex configurations.  The device serves up a web app that is a MicroPython IDE, accessible by any device with a modern browser.  Tablets, Chromebooks, and PCs can all access it the same way.  [More information here](https://github.com/tdhoward/TartLab), if you're curious.

I would love to compare notes and help with testing and development on this project.  My email address is my GH username at gmail.com.  Feel free to email whenever.

Thanks again!

**Comment by joshwand** [comment]
Ah looks like lots has changed since I last looked at packages.json, and I didn't even notice the install.py in the root! I will give it another go. 

FWIW I am using it on a Waveshare ESP32-S3-LCD-1.28 which uses gc9a01 and ships with a micropython build that has an slightly older version of [russ hugh's C drivers ](https://github.com/russhughes/gc9a01_mpy) compiled in. (Unfortunately that driver does not inherit from framebuf).  I haven't had any luck with the various userspace drivers but I probably could have spent more time making it work. 

Not using LVGL since I couldn't make heads or tails of the competing bindings, and the widgets weren't a good fit for my UI.

For now I have implemented my own double-buffering interface that blits changed regions to the display, but I have to know the bounding boxes since comparing the buffers in micropython is too slow and I never went down the path of compiling in ulab. 

`mpremote mount .` was too slow for reading fonts, so I am using rshell's rsync command which works great.

**Comment by bdbarnett** [comment]
@tdhoward Thank you for the feedback.  Your project seems like a great idea.  I have corrected the naming / package errors and the Wokwi example is working now.

You mentioned the ST7796.  When I test on hardware, the WT32SC01-Plus is what I use most.  It has an ST7796 controller, but it is wired as I80 instead of SPI.  I created a [t-display-s3-pro board_config.py](https://github.com/bdbarnett/mpdisplay/tree/main/board_configs/t-display-s3-pro) for you to try.  Please let me know whether it works for you.  It will probably need some modifications.  I commented it well, so hopefully it's easy to dial in.

I appreciate any input you can give me, whether it's just reporting bugs or telling me what I can add to meet your needs or even submitting a pull request.  I'd be glad to compare notes.  I'm fine with emailing and will send you my email address shortly, but I prefer most discussions to be in the [project's Discussions](https://github.com/bdbarnett/mpdisplay/discussions) to encourage others to join in as well.  By all means if you ever want to setup a web meeting to discuss something that's easier said than typed, just let me know.  Thank you again!

@joshwand I just put the install.py up after I read your last message, so you didn't overlook it.  I've been putting all my time into coding and preparing for packaging, for both MIP and PIP, and I've fallen way behind on documentation.  I hope to catch up within the next couple weeks.

I have a few of the Seeed Studio Round Display for Xiao (awful name!) that have the GC9A01 controller.  You've probably noticed the [framebuf_plus.FrameBuffer](https://github.com/bdbarnett/mpdisplay/tree/main/src/lib/pyd_gl/framebuf_plus) class is a subclass of the built-in (at least on MicroPython) framebuf.FrameBuffer, but all of it's primitives return an Area object showing what has changed.  In fact, all of the drawing primitives, including those in bmp565, pbm, binfont, tft_text and tft_write return the dirty Area.  If you need to import Area yourself, it's best to import it from either basedisplay or pyd_gl, for instance:
```
from basedisplay import Area # or
from pyd_gl import Area
area1 = Area(0, 0, 20, 20)
```
There are some features in Area that may be useful.  If you want to get the bounding box for 2 bounding boxes (Areas), simply add them together:  `area3 = area1 + area2`.  The == and != operators also work.  Unpacking also works, so instead of writing `dirty.x, dirty.y, dirty.w, dirty.h` in the parameters for blit_rect, you can just write `*dirty`.

One last thing to mention.  The [displaybuf.DisplayBuffer](https://github.com/bdbarnett/mpdisplay/tree/main/src/lib/pyd_gl/displaybuf) class is a framebuf_plus.Framebuffer meant to be used for the whole display.  I got the base of it from peterhinch's work.  There are several examples that use it either by importing it directly or through color_setup.py or hardware_setup.py, but here is a short example:
```
from board_config import display_drv
from pyd_gl.displaybuf import DisplayBuffer

canvas = DisplayBuffer(display_drv)
dirty = canvas.round_rect(0, 0, 40, 10, 5, 0x1234)
canvas.show(dirty)
```
Thanks for your feedback.  Let me know if I can help in any way.  I'm going to close this issue, but feel free to create another or startup a [Discussion](https://github.com/bdbarnett/mpdisplay/discussions).
