### ISSUE TITLE
Got a present for ya

### ISSUE THREAD

**Issue by kdschlosser** [bdbarnett/mpdisplay#4]
This is for STM32

[mphal.zip](https://github.com/bdbarnett/mpdisplay/files/13920964/mphal.zip)

**Comment by kdschlosser** [comment]
and here is a C bitbang driver for the I80 bus. I am working on the SPI, RGB and I2C still. This will not support DMA memory so single buffers only. I have not tested it, actually I have not even tried to compile it so I am sure there is going to be a plethora of errors. There are 2 issues with my code, the first is I am not a C programmer and the second is my keyboard is going bad and keys are not pressing or getting stuck down. That last one only makes things all kinds of worse. 

I am sure you can clean it up but it is sound.  That should fox the speed issue with your current implementation. I am leveraging mphalport to provide everything I need. 


[lcd_bus.zip](https://github.com/bdbarnett/mpdisplay/files/13925641/lcd_bus.zip)

**Comment by bdbarnett** [comment]
Very cool!  It'll take me a bit to wrap my head around it.  I'll check it out.

I wrote and tested the MicroPython implementation of I80Bus using what I have, which are all ESP32 boards except one STM32H7 that I'm not very familiar with yet.  My WT32SC01-Plus has non-consecutive pins on the 8-pin display bus, so I had to use a lookup table to convert the 8-bit value being written to the display into a 32-bit value and mask to use SET or CLR with machine.mem32.  Not only does the WT32SC01-Plus not use consecutive pin numbers, it doesn't use pins all from the same 32-bit address space.  All of the pins except one are <= 31, but that one pin requires adding a second lookup table.

Because of the way I'm having to use lookup tables and the way I'm finding which register belongs to which pin on which platform, it doesn't work with pin names.  I'm not going to address that because it looks like MicroPython 2.0 may solve that problem for me.

**Comment by kdschlosser** [comment]
This is better... You are going to like this wayyy more...

again I have not tested or compiled this yet so it is still very much a work in progress


[driver.zip](https://github.com/bdbarnett/mpdisplay/files/13927437/driver.zip)

It shares the majority of the lcd_bus code between the different types of busses and also between an ESP32 compilation and other boards. I still have to finish up writing the non ESP32 SPI and I2C. I don't think I am going to even try to write a bit bang for the RGB ya never know tho. I8080 is in there for both 8 and 16 bit. There is also a non ESP32 version of heap_caps as well. I will be reducing that into  single module to make it easier to maintain as well.

**Comment by kdschlosser** [comment]
MicroPython 2.0? there is no branch for it at all. and I have not come across any talk about it.

**Comment by kdschlosser** [comment]
Yeah OK so I did see a reference to it once. a very long time ago as in 8 years ago. It fizzled and never went anywhere. It was supposed to have been released some time in 2017 but that never happened. You will be waiting for a really long time for it to get released.

**Comment by kdschlosser** [comment]
maybe you know how to correct this issue I am having. I cannot figure it out for the life of me. I know how I fixed it in the current version of the bus drivers but I didn't like moving the function definitions into the header file. I wanted to keep the functions in the source file and only declare them in the header file.

[driver.zip](https://github.com/bdbarnett/mpdisplay/files/13934911/driver.zip)

Only compile for the ESP32-S3 for the time being. It compiles but it won't link. I am going to work on the rest of it once I get that board up and running. I want to pull in the bit bang version of the I80 bus for the ESP32 variants that do not support the hardware version. Once I get it to compile properly for the ESP32 S3 I will get the code to compile for the other boards, then I will circle back and get the other variants of the ESP32 compiling.

There is going to be some larger changes where the entire thing compiles at the same time using macros to direct what to do. I haven't fully gotten to that point yet.

**Comment by bdbarnett** [comment]
I like the new structure a lot!  You've made a ton of progress!

I had a similar problem with compiling but not linking when I wrote C drivers, and it came down to not having includes in the correct places.  I only fixed it by trial and error, but never figured out what the actual cause was.

Check this out:
https://docs.micropython.org/en/latest/reference/micropython2_migration.html.

This was just added in MP 1.22:
```
make MICROPY_PREVIEW_VERSION_2=1
```

**Comment by kdschlosser** [comment]
https://github.com/micropython/micropython/issues/2486

was talked about a longggg time ago

**Comment by kdschlosser** [comment]
my issue is I want to be able to share the functions across all of the different busses. so the MP_DEFINE_CONST_FUN_OBJ_KW type macros that are used need to be in the header files. I have tried every which way to keep the functions in the source files  and I always get this error.

```
/home/kgschlosser/.espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: CMakeFiles/micropython.elf.dir/home/kgschlosser/lv_binding_micropython/driver/lcd_bus/esp32_src/rgb_bus.c.obj:(.rodata+0x90): multiple definition of `mp_lcd_bus_locals_dict'; CMakeFiles/micropython.elf.dir/home/kgschlosser/lv_binding_micropython/driver/lcd_bus/modlcd_bus.c.obj:(.rodata+0x90): first defined here
```

if I move the function into the header file the problem goes away. It doesn't make any sense.


ORRRRR

I bet I know what I need to do.

**Comment by kdschlosser** [comment]
YUP!!!! That worked!!!

I had to declare them as `extern`

**Comment by kdschlosser** [comment]
so now I am onto the build for other boards to see if that works. before I do that I am going to change up how things are getting compiled.

**Comment by kdschlosser** [comment]
https://github.com/kdschlosser/mp_heap_caps
https://github.com/kdschlosser/mp_lcd_bus
